name: Generate and Deploy Report

on:
  schedule:
    # Run every 24 hours at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build TypeScript
        run: npm run build
      
      - name: Generate report
        env:
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_REGION: ${{ secrets.S3_REGION }}
        run: |
          mkdir -p reports
          npm start
      
      - name: Copy report to public folder
        run: |
          mkdir -p public
          # Find the most recent report
          LATEST_REPORT=$(ls -t reports/*.html | head -1)
          if [ -f "$LATEST_REPORT" ]; then
            cp "$LATEST_REPORT" public/index.html
            echo "Report copied to public/index.html"
          else
            echo "No report found!"
            exit 1
          fi
      
      - name: Commit report to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/
          git diff --staged --quiet || git commit -m "Update optimization report - $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main || true
      
      - name: Trigger Vercel Deploy
        run: |
          if [ -n "${{ secrets.VERCEL_DEPLOY_HOOK }}" ]; then
            curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
            echo "✅ Vercel deployment triggered successfully"
          else
            echo "⚠️ VERCEL_DEPLOY_HOOK secret not set"
            echo "To set up automatic deployments:"
            echo "1. Go to your Vercel project settings"
            echo "2. Navigate to Git > Deploy Hooks"
            echo "3. Create a deploy hook"
            echo "4. Add it as VERCEL_DEPLOY_HOOK secret in GitHub"
          fi