name: Trigger Vercel Rebuild

on:
  schedule:
    # Run every 24 hours at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  trigger-rebuild:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Vercel Deploy Hook
        run: |
          if [ -n "${{ secrets.VERCEL_DEPLOY_HOOK }}" ]; then
            curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
            echo "✅ Vercel rebuild triggered successfully"
          else
            echo "⚠️ VERCEL_DEPLOY_HOOK secret not set"
            echo "To set up automatic rebuilds:"
            echo "1. Go to your Vercel project settings"
            echo "2. Navigate to Git > Deploy Hooks"
            echo "3. Create a deploy hook"
            echo "4. Add it as VERCEL_DEPLOY_HOOK secret in GitHub"
          fi